services:
  - docker
env:
  global:
  - AUTHOR_EMAIL=primeroz@gmail.com
  - REGISTRY_USERNAME=primeroz
  - REGISTRY=docker.io
language: go
go: 1.9.3
install: true
before_script:
  - curl -Lo /tmp/bash_unit https://raw.githubusercontent.com/pgrange/bash_unit/v1.6.1/bash_unit
  - chmod a+x /tmp/bash_unit
script:
  - make test
  - GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -ldflags "-X main.gitsha=${TRAVIS_TAG:-git+${TRAVIS_COMMIT}}" -o bin/vault-sidekick_linux_amd64;
